name: Run Kafka Producer

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser pymongo kafka-python

    - name: Create Certificate Files
      run: |
        mkdir -p ./kafkaCerts
        echo "${{ secrets.KAFKA_CERT_CA_CONTENT }}" | base64 --decode > ./kafkaCerts/ca.pem
        echo "${{ secrets.KAFKA_CERT_FILE_CONTENT }}" | base64 --decode > ./kafkaCerts/service.cert
        echo "${{ secrets.KAFKA_CERT_KEY_CONTENT }}" | base64 --decode > ./kafkaCerts/service.key

    - name: Run Kafka Producer
      env:  # Set environment variables
        MONGO_URI: ${{ secrets.MONGO_URI }}  # MongoDB URI
        KAFKA_SERVER: ${{ secrets.KAFKA_SERVER }}  # Kafka server address
      run: |
        python producer.py  # Adjust this to the path of your script
