name: RSS Feed Parser

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the version of Python you want

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo feedparser kafka-python # Add any other dependencies here

    - name: Run RSS Feed Parser
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}  # Set environment variable for MongoDB URI
      run: |
        python producer.py  
