name: Run Kafka Producer

on:
  push:
    branches:
      - main  # Change to your default branch if needed
  # schedule:
  #   - cron: '0 * * * *'  # Runs every hour at the start of the hour
  # workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser pymongo kafka-python python-dotenv

    # - name: Create Certificate Files
    #   run: |
    #     mkdir -p ./kafkaCerts
    #     echo "${{ secrets.KAFKA_CERT_CA_CONTENT }}" | base64 --decode > ./kafkaCerts/ca.pem
    #     echo "${{ secrets.KAFKA_CERT_FILE_CONTENT }}" | base64 --decode > ./kafkaCerts/service.cert
    #     echo "${{ secrets.KAFKA_CERT_KEY_CONTENT }}" | base64 --decode > ./kafkaCerts/service.key

    - name: Run Kafka Producer
      env:  # Set environment variables
        MONGO_URI: ${{ secrets.MONGO_URI }}  # MongoDB URI
        CLOUD_KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.CLOUD_KAFKA_BOOTSTRAP_SERVERS }}  # Kafka server address
        CLOUD_KAFKA_API_KEY: ${{ secrets.CLOUD_KAFKA_API_KEY }}
        CLOUD_KAFKA_API_SECRET: ${{ secrets.CLOUD_KAFKA_API_SECRET }}
      run: |
        python producer.py  # Adjust this to the path of your script
